<?php

return [
    'timezone' => [
        'Asia/Kabul' => 'Afghanistan',
        'Europe/Tirane' => 'Albania',
        'Africa/Algiers' => 'Algeria',
        'Pacific/Pago_Pago' => 'American Samoa',
        'Europe/Andorra' => 'Andorra',
        'Africa/Luanda' => 'Angola',
        'America/Anguilla' => 'Anguilla',
        'Antarctica/Casey' => 'Antarctica',
        'Antarctica/Davis' => 'Antarctica',
        'Antarctica/DumontDUrville' => 'Antarctica',
        'Antarctica/Mawson' => 'Antarctica',
        'Antarctica/McMurdo' => 'Antarctica',
        'Antarctica/Palmer' => 'Antarctica',
        'Antarctica/Rothera' => 'Antarctica',
        'Antarctica/Syowa' => 'Antarctica',
        'Antarctica/Troll' => 'Antarctica',
        'Antarctica/Vostok' => 'Antarctica',
        'America/Antigua' => 'Antigua and Barbuda',
        'America/Argentina/Buenos_Aires' => 'Argentina',
        'America/Argentina/Catamarca' => 'Argentina',
        'America/Argentina/Cordoba' => 'Argentina',
        'America/Argentina/Jujuy' => 'Argentina',
        'America/Argentina/La_Rioja' => 'Argentina',
        'America/Argentina/Mendoza' => 'Argentina',
        'America/Argentina/Rio_Gallegos' => 'Argentina',
        'America/Argentina/Salta' => 'Argentina',
        'America/Argentina/San_Juan' => 'Argentina',
        'America/Argentina/San_Luis' => 'Argentina',
        'America/Argentina/Tucuman' => 'Argentina',
        'America/Argentina/Ushuaia' => 'Argentina',
        'Asia/Yerevan' => 'Armenia',
        'America/Aruba' => 'Aruba',
        'Antarctica/Macquarie' => 'Australia',
        'Australia/Adelaide' => 'Australia',
        'Australia/Brisbane' => 'Australia',
        'Australia/Broken_Hill' => 'Australia',
        'Australia/Darwin' => 'Australia',
        'Australia/Eucla' => 'Australia',
        'Australia/Hobart' => 'Australia',
        'Australia/Lindeman' => 'Australia',
        'Australia/Lord_Howe' => 'Australia',
        'Australia/Melbourne' => 'Australia',
        'Australia/Perth' => 'Australia',
        'Australia/Sydney' => 'Australia',
        'Europe/Vienna' => 'Austria',
        'Asia/Baku' => 'Azerbaijan',
        'America/Nassau' => 'Bahamas',
        'Asia/Bahrain' => 'Bahrain',
        'Asia/Dhaka' => 'Bangladesh',
        'America/Barbados' => 'Barbados',
        'Europe/Minsk' => 'Belarus',
        'Europe/Brussels' => 'Belgium',
        'America/Belize' => 'Belize',
        'Africa/Porto-Novo' => 'Benin',
        'Atlantic/Bermuda' => 'Bermuda',
        'Asia/Thimphu' => 'Bhutan',
        'Plurinational State of' => 'Bolivia',
        'Sint Eustatius and Saba' => 'Bonaire',
        'Europe/Sarajevo' => 'Bosnia and Herzegovina',
        'Africa/Gaborone' => 'Botswana',
        'America/Araguaina' => 'Brazil',
        'America/Bahia' => 'Brazil',
        'America/Belem' => 'Brazil',
        'America/Boa_Vista' => 'Brazil',
        'America/Campo_Grande' => 'Brazil',
        'America/Cuiaba' => 'Brazil',
        'America/Eirunepe' => 'Brazil',
        'America/Fortaleza' => 'Brazil',
        'America/Maceio' => 'Brazil',
        'America/Manaus' => 'Brazil',
        'America/Noronha' => 'Brazil',
        'America/Porto_Velho' => 'Brazil',
        'America/Recife' => 'Brazil',
        'America/Rio_Branco' => 'Brazil',
        'America/Santarem' => 'Brazil',
        'America/Sao_Paulo' => 'Brazil',
        'Indian/Chagos' => 'British Indian Ocean Territory',
        'Asia/Brunei' => 'Brunei Darussalam',
        'Europe/Sofia' => 'Bulgaria',
        'Africa/Ouagadougou' => 'Burkina Faso',
        'Africa/Bujumbura' => 'Burundi',
        'Asia/Phnom_Penh' => 'Cambodia',
        'Africa/Douala' => 'Cameroon',
        'America/Atikokan' => 'Canada',
        'America/Blanc-Sablon' => 'Canada',
        'America/Cambridge_Bay' => 'Canada',
        'America/Creston' => 'Canada',
        'America/Dawson' => 'Canada',
        'America/Dawson_Creek' => 'Canada',
        'America/Edmonton' => 'Canada',
        'America/Fort_Nelson' => 'Canada',
        'America/Glace_Bay' => 'Canada',
        'America/Goose_Bay' => 'Canada',
        'America/Halifax' => 'Canada',
        'America/Inuvik' => 'Canada',
        'America/Iqaluit' => 'Canada',
        'America/Moncton' => 'Canada',
        'America/Nipigon' => 'Canada',
        'America/Pangnirtung' => 'Canada',
        'America/Rainy_River' => 'Canada',
        'America/Rankin_Inlet' => 'Canada',
        'America/Regina' => 'Canada',
        'America/Resolute' => 'Canada',
        'America/St_Johns' => 'Canada',
        'America/Swift_Current' => 'Canada',
        'America/Thunder_Bay' => 'Canada',
        'America/Toronto' => 'Canada',
        'America/Vancouver' => 'Canada',
        'America/Whitehorse' => 'Canada',
        'America/Winnipeg' => 'Canada',
        'America/Yellowknife' => 'Canada',
        'Atlantic/Cape_Verde' => 'Cape Verde',
        'America/Cayman' => 'Cayman Islands',
        'Africa/Bangui' => 'Central African Republic',
        'Africa/Ndjamena' => 'Chad',
        'America/Punta_Arenas' => 'Chile',
        'America/Santiago' => 'Chile',
        'Pacific/Easter' => 'Chile',
        'Asia/Shanghai' => 'China',
        'Asia/Urumqi' => 'China',
        'Indian/Christmas' => 'Christmas Island',
        'Indian/Cocos' => 'Cocos (Keeling) Islands',
        'America/Bogota' => 'Colombia',
        'Indian/Comoro' => 'Comoros',
        'Pacific/Rarotonga' => 'Cook Islands',
        'America/Costa_Rica' => 'Costa Rica',
        'Europe/Zagreb' => 'Croatia',
        'America/Havana' => 'Cuba',
        'America/Curacao' => 'Curaçao',
        'Asia/Famagusta' => 'Cyprus',
        'Asia/Nicosia' => 'Cyprus',
        'Europe/Prague' => 'Czech Republic',
        'Africa/Abidjan' => 'Côte d Ivoire',
        'Europe/Copenhagen' => 'Denmark',
        'Africa/Djibouti' => 'Djibouti',
        'America/Dominica' => 'Dominica',
        'America/Santo_Domingo' => 'Dominican Republic',
        'America/Guayaquil' => 'Ecuador',
        'Pacific/Galapagos' => 'Ecuador',
        'Africa/Cairo' => 'Egypt',
        'America/El_Salvador' => 'El Salvador',
        'Africa/Malabo' => 'Equatorial Guinea',
        'Africa/Asmara' => 'Eritrea',
        'Europe/Tallinn' => 'Estonia',
        'Africa/Addis_Ababa' => 'Ethiopia',
        'Atlantic/Stanley' => 'Falkland Islands (Malvinas)',
        'Atlantic/Faroe' => 'Faroe Islands',
        'Pacific/Fiji' => 'Fiji',
        'Europe/Helsinki' => 'Finland',
        'Europe/Paris' => 'France',
        'America/Cayenne' => 'French Guiana',
        'Pacific/Gambier' => 'French Polynesia',
        'Pacific/Marquesas' => 'French Polynesia',
        'Pacific/Tahiti' => 'French Polynesia',
        'Indian/Kerguelen' => 'French Southern Territories',
        'Africa/Libreville' => 'Gabon',
        'Africa/Banjul' => 'Gambia',
        'Asia/Tbilisi' => 'Georgia',
        'Europe/Berlin' => 'Germany',
        'Europe/Busingen' => 'Germany',
        'Africa/Accra' => 'Ghana',
        'Europe/Gibraltar' => 'Gibraltar',
        'Europe/Athens' => 'Greece',
        'America/Danmarkshavn' => 'Greenland',
        'America/Nuuk' => 'Greenland',
        'America/Scoresbysund' => 'Greenland',
        'America/Thule' => 'Greenland',
        'America/Grenada' => 'Grenada',
        'America/Guadeloupe' => 'Guadeloupe',
        'Pacific/Guam' => 'Guam',
        'America/Guatemala' => 'Guatemala',
        'Europe/Guernsey' => 'Guernsey',
        'Africa/Conakry' => 'Guinea',
        'Africa/Bissau' => 'Guinea-Bissau',
        'America/Guyana' => 'Guyana',
        'America/Port-au-Prince' => 'Haiti',
        'Europe/Vatican' => 'Holy See (Vatican City State)',
        'America/Tegucigalpa' => 'Honduras',
        'Asia/Hong_Kong' => 'Hong Kong',
        'Europe/Budapest' => 'Hungary',
        'Atlantic/Reykjavik' => 'Iceland',
        'Asia/Kolkata' => 'India',
        'Asia/Jakarta' => 'Indonesia',
        'Asia/Jayapura' => 'Indonesia',
        'Asia/Makassar' => 'Indonesia',
        'Asia/Pontianak' => 'Indonesia',
        'Islamic Republic of' => 'Iran',
        'Asia/Baghdad' => 'Iraq',
        'Europe/Dublin' => 'Ireland',
        'Europe/Isle_of_Man' => 'Isle of Man',
        'Asia/Jerusalem' => 'Israel',
        'Europe/Rome' => 'Italy',
        'America/Jamaica' => 'Jamaica',
        'Asia/Tokyo' => 'Japan',
        'Europe/Jersey' => 'Jersey',
        'Asia/Amman' => 'Jordan',
        'Asia/Almaty' => 'Kazakhstan',
        'Asia/Aqtau' => 'Kazakhstan',
        'Asia/Aqtobe' => 'Kazakhstan',
        'Asia/Atyrau' => 'Kazakhstan',
        'Asia/Oral' => 'Kazakhstan',
        'Asia/Qostanay' => 'Kazakhstan',
        'Asia/Qyzylorda' => 'Kazakhstan',
        'Africa/Nairobi' => 'Kenya',
        'Pacific/Kanton' => 'Kiribati',
        'Pacific/Kiritimati' => 'Kiribati',
        'Pacific/Tarawa' => 'Kiribati',
        'Democratic Peoples Republic of' => 'Korea',
        'Asia/Kuwait' => 'Kuwait',
        'Asia/Bishkek' => 'Kyrgyzstan',
        'Asia/Vientiane' => 'Lao Peoples Democratic Republic',
        'Europe/Riga' => 'Latvia',
        'Asia/Beirut' => 'Lebanon',
        'Africa/Maseru' => 'Lesotho',
        'Africa/Monrovia' => 'Liberia',
        'Africa/Tripoli' => 'Libya',
        'Europe/Vaduz' => 'Liechtenstein',
        'Europe/Vilnius' => 'Lithuania',
        'Europe/Luxembourg' => 'Luxembourg',
        'Asia/Macau' => 'Macao',
        'the Former Yugoslav Republic of' => 'Macedonia',
        'Indian/Antananarivo' => 'Madagascar',
        'Africa/Blantyre' => 'Malawi',
        'Asia/Kuala_Lumpur' => 'Malaysia',
        'Asia/Kuching' => 'Malaysia',
        'Indian/Maldives' => 'Maldives',
        'Africa/Bamako' => 'Mali',
        'Europe/Malta' => 'Malta',
        'Pacific/Kwajalein' => 'Marshall Islands',
        'Pacific/Majuro' => 'Marshall Islands',
        'America/Martinique' => 'Martinique',
        'Africa/Nouakchott' => 'Mauritania',
        'Indian/Mauritius' => 'Mauritius',
        'Indian/Mayotte' => 'Mayotte',
        'America/Bahia_Banderas' => 'Mexico',
        'America/Cancun' => 'Mexico',
        'America/Chihuahua' => 'Mexico',
        'America/Hermosillo' => 'Mexico',
        'America/Matamoros' => 'Mexico',
        'America/Mazatlan' => 'Mexico',
        'America/Merida' => 'Mexico',
        'America/Mexico_City' => 'Mexico',
        'America/Monterrey' => 'Mexico',
        'America/Ojinaga' => 'Mexico',
        'America/Tijuana' => 'Mexico',
        'Europe/Monaco' => 'Monaco',
        'Asia/Choibalsan' => 'Mongolia',
        'Asia/Hovd' => 'Mongolia',
        'Asia/Ulaanbaatar' => 'Mongolia',
        'Europe/Podgorica' => 'Montenegro',
        'America/Montserrat' => 'Montserrat',
        'Africa/Casablanca' => 'Morocco',
        'Africa/Maputo' => 'Mozambique',
        'Asia/Yangon' => 'Myanmar',
        'Africa/Windhoek' => 'Namibia',
        'Pacific/Nauru' => 'Nauru',
        'Asia/Kathmandu' => 'Nepal',
        'Europe/Amsterdam' => 'Netherlands',
        'Pacific/Noumea' => 'New Caledonia',
        'Pacific/Auckland' => 'New Zealand',
        'Pacific/Chatham' => 'New Zealand',
        'America/Managua' => 'Nicaragua',
        'Africa/Niamey' => 'Niger',
        'Africa/Lagos' => 'Nigeria',
        'Pacific/Niue' => 'Niue',
        'Pacific/Norfolk' => 'Norfolk Island',
        'Pacific/Saipan' => 'Northern Mariana Islands',
        'Europe/Oslo' => 'Norway',
        'Asia/Muscat' => 'Oman',
        'Asia/Karachi' => 'Pakistan',
        'Pacific/Palau' => 'Palau',
        'America/Panama' => 'Panama',
        'Pacific/Bougainville' => 'Papua New Guinea',
        'Pacific/Port_Moresby' => 'Papua New Guinea',
        'America/Asuncion' => 'Paraguay',
        'America/Lima' => 'Peru',
        'Asia/Manila' => 'Philippines',
        'Pacific/Pitcairn' => 'Pitcairn',
        'Europe/Warsaw' => 'Poland',
        'Atlantic/Azores' => 'Portugal',
        'Atlantic/Madeira' => 'Portugal',
        'Europe/Lisbon' => 'Portugal',
        'America/Puerto_Rico' => 'Puerto Rico',
        'Asia/Qatar' => 'Qatar',
        'Europe/Bucharest' => 'Romania',
        'Asia/Anadyr' => 'Russian Federation',
        'Asia/Barnaul' => 'Russian Federation',
        'Asia/Chita' => 'Russian Federation',
        'Asia/Irkutsk' => 'Russian Federation',
        'Asia/Kamchatka' => 'Russian Federation',
        'Asia/Khandyga' => 'Russian Federation',
        'Asia/Krasnoyarsk' => 'Russian Federation',
        'Asia/Magadan' => 'Russian Federation',
        'Asia/Novokuznetsk' => 'Russian Federation',
        'Asia/Novosibirsk' => 'Russian Federation',
        'Asia/Omsk' => 'Russian Federation',
        'Asia/Sakhalin' => 'Russian Federation',
        'Asia/Srednekolymsk' => 'Russian Federation',
        'Asia/Tomsk' => 'Russian Federation',
        'Asia/Ust-Nera' => 'Russian Federation',
        'Asia/Vladivostok' => 'Russian Federation',
        'Asia/Yakutsk' => 'Russian Federation',
        'Asia/Yekaterinburg' => 'Russian Federation',
        'Europe/Astrakhan' => 'Russian Federation',
        'Europe/Kaliningrad' => 'Russian Federation',
        'Europe/Kirov' => 'Russian Federation',
        'Europe/Moscow' => 'Russian Federation',
        'Europe/Samara' => 'Russian Federation',
        'Europe/Saratov' => 'Russian Federation',
        'Europe/Ulyanovsk' => 'Russian Federation',
        'Europe/Volgograd' => 'Russian Federation',
        'Africa/Kigali' => 'Rwanda',
        'Indian/Reunion' => 'Réunion',
        'America/St_Barthelemy' => 'Saint Barthélemy',
        'Ascension and Tristan da Cunha' => 'Saint Helena',
        'America/St_Kitts' => 'Saint Kitts and Nevis',
        'America/St_Lucia' => 'Saint Lucia',
        'America/Marigot' => 'Saint Martin (French part)',
        'America/Miquelon' => 'Saint Pierre and Miquelon',
        'America/St_Vincent' => 'Saint Vincent and the Grenadines',
        'Pacific/Apia' => 'Samoa',
        'Europe/San_Marino' => 'San Marino',
        'Africa/Sao_Tome' => 'Sao Tome and Principe',
        'Asia/Riyadh' => 'Saudi Arabia',
        'Africa/Dakar' => 'Senegal',
        'Europe/Belgrade' => 'Serbia',
        'Indian/Mahe' => 'Seychelles',
        'Africa/Freetown' => 'Sierra Leone',
        'Asia/Singapore' => 'Singapore',
        'America/Lower_Princes' => 'Sint Maarten (Dutch part)',
        'Europe/Bratislava' => 'Slovakia',
        'Europe/Ljubljana' => 'Slovenia',
        'Pacific/Guadalcanal' => 'Solomon Islands',
        'Africa/Mogadishu' => 'Somalia',
        'Africa/Johannesburg' => 'South Africa',
        'Atlantic/South_Georgia' => 'South Georgia and the South Sandwich Islands',
        'Africa/Juba' => 'South Sudan',
        'Africa/Ceuta' => 'Spain',
        'Atlantic/Canary' => 'Spain',
        'Europe/Madrid' => 'Spain',
        'Asia/Colombo' => 'Sri Lanka',
        'Africa/Khartoum' => 'Sudan',
        'America/Paramaribo' => 'Suriname',
        'Arctic/Longyearbyen' => 'Svalbard and Jan Mayen',
        'Africa/Mbabane' => 'Swaziland',
        'Europe/Stockholm' => 'Sweden',
        'Europe/Zurich' => 'Switzerland',
        'Asia/Damascus' => 'Syrian Arab Republic',
        'Province of China' => 'Taiwan',
        'Asia/Dushanbe' => 'Tajikistan',
        'United Republic of' => 'Tanzania',
        'Asia/Bangkok' => 'Thailand',
        'Asia/Dili' => 'Timor-Leste',
        'Africa/Lome' => 'Togo',
        'Pacific/Fakaofo' => 'Tokelau',
        'Pacific/Tongatapu' => 'Tonga',
        'America/Port_of_Spain' => 'Trinidad and Tobago',
        'Africa/Tunis' => 'Tunisia',
        'Europe/Istanbul' => 'Turkey',
        'Asia/Ashgabat' => 'Turkmenistan',
        'America/Grand_Turk' => 'Turks and Caicos Islands',
        'Pacific/Funafuti' => 'Tuvalu',
        'Africa/Kampala' => 'Uganda',
        'Europe/Kiev' => 'Ukraine',
        'Europe/Simferopol' => 'Ukraine',
        'Europe/Uzhgorod' => 'Ukraine',
        'Europe/Zaporozhye' => 'Ukraine',
        'Asia/Dubai' => 'United Arab Emirates',
        'Europe/London' => 'United Kingdom',
        'America/Adak' => 'United States',
        'America/Anchorage' => 'United States',
        'America/Boise' => 'United States',
        'America/Chicago' => 'United States',
        'America/Denver' => 'United States',
        'America/Detroit' => 'United States',
        'America/Indiana/Indianapolis' => 'United States',
        'America/Indiana/Knox' => 'United States',
        'America/Indiana/Marengo' => 'United States',
        'America/Indiana/Petersburg' => 'United States',
        'America/Indiana/Tell_City' => 'United States',
        'America/Indiana/Vevay' => 'United States',
        'America/Indiana/Vincennes' => 'United States',
        'America/Indiana/Winamac' => 'United States',
        'America/Juneau' => 'United States',
        'America/Kentucky/Louisville' => 'United States',
        'America/Kentucky/Monticello' => 'United States',
        'America/Los_Angeles' => 'United States',
        'America/Menominee' => 'United States',
        'America/Metlakatla' => 'United States',
        'America/New_York' => 'United States',
        'America/Nome' => 'United States',
        'America/North_Dakota/Beulah' => 'United States',
        'America/North_Dakota/Center' => 'United States',
        'America/North_Dakota/New_Salem' => 'United States',
        'America/Phoenix' => 'United States',
        'America/Sitka' => 'United States',
        'America/Yakutat' => 'United States',
        'Pacific/Honolulu' => 'United States',
        'Pacific/Midway' => 'United States Minor Outlying Islands',
        'Pacific/Wake' => 'United States Minor Outlying Islands',
        'America/Montevideo' => 'Uruguay',
        'Asia/Samarkand' => 'Uzbekistan',
        'Asia/Tashkent' => 'Uzbekistan',
        'Pacific/Efate' => 'Vanuatu',
        'Bolivarian Republic of' => 'Venezuela',
        'Asia/Ho_Chi_Minh' => 'Viet Nam',
        'British' => 'Virgin Islands',
        'U.S.' => 'Virgin Islands',
        'Pacific/Wallis' => 'Wallis and Futuna',
        'Africa/El_Aaiun' => 'Western Sahara',
        'Asia/Aden' => 'Yemen',
        'Africa/Lusaka' => 'Zambia',
        'Africa/Harare' => 'Zimbabwe',
        'Europe/Mariehamn' => 'Åland Islands'
    ],
    'currency_list' => [
        "AFA"   => [ "name"=>"Afghan Afghani","symbol"=>"؋" ],
        "ALL"   => [ "name"=>"Albanian Lek","symbol"=>"Lek" ],
        "DZD"   => [ "name"=>"Algerian Dinar","symbol"=>"دج" ],
        "AOA"   => [ "name"=>"Angolan Kwanza","symbol"=>"Kz" ],
        "ARS"   => [ "name"=>"Argentine Peso","symbol"=>"$" ],
        "AMD"   => [ "name"=>"Armenian Dram","symbol"=>"֏" ],
        "AWG"   => [ "name"=>"Aruban Florin","symbol"=>"ƒ" ],
        "AUD"   => [ "name"=>"Australian Dollar","symbol"=>"$" ],
        "AZN"   => [ "name"=>"Azerbaijani Manat","symbol"=>"m" ],
        "BSD"   => [ "name"=>"Bahamian Dollar","symbol"=>"B$" ],
        "BHD"   => [ "name"=>"Bahraini Dinar","symbol"=>".د.ب" ],
        "BDT"   => [ "name"=>"Bangladeshi Taka","symbol"=>"৳" ],
        "BBD"   => [ "name"=>"Barbadian Dollar","symbol"=>"Bds$" ],
        "BYR"   => [ "name"=>"Belarusian Ruble","symbol"=>"Br" ],
        "BEF"   => [ "name"=>"Belgian Franc","symbol"=>"fr" ],
        "BZD"   => [ "name"=>"Belize Dollar","symbol"=>"$" ],
        "BMD"   => [ "name"=>"Bermudan Dollar","symbol"=>"$" ],
        "BTN"   => [ "name"=>"Bhutanese Ngultrum","symbol"=>"Nu." ],
        "BTC"   => [ "name"=>"Bitcoin","symbol"=>"฿" ],
        "BOB"   => [ "name"=>"Bolivian Boliviano","symbol"=>"Bs." ],
        "BAM"   => [ "name"=>"Bosnia-Herzegovina Convertible Mark","symbol"=>"KM" ],
        "BWP"   => [ "name"=>"Botswanan Pula","symbol"=>"P" ],
        "BRL"   => [ "name"=>"Brazilian Real","symbol"=>"R$" ],
        "GBP"   => [ "name"=>"British Pound Sterling","symbol"=>"£" ],
        "BND"   => [ "name"=>"Brunei Dollar","symbol"=>"B$" ],
        "BGN"   => [ "name"=>"Bulgarian Lev","symbol"=>"Лв." ],
        "BIF"   => [ "name"=>"Burundian Franc","symbol"=>"FBu" ],
        "KHR"   => [ "name"=>"Cambodian Riel","symbol"=>"KHR" ],
        "CAD"   => [ "name"=>"Canadian Dollar","symbol"=>"$" ],
        "CVE"   => [ "name"=>"Cape Verdean Escudo","symbol"=>"$" ],
        "KYD"   => [ "name"=>"Cayman Islands Dollar","symbol"=>"$" ],
        "XOF"   => [ "name"=>"CFA Franc BCEAO","symbol"=>"CFA" ],
        "XAF"   => [ "name"=>"CFA Franc BEAC","symbol"=>"FCFA" ],
        "XPF"   => [ "name"=>"CFP Franc","symbol"=>"₣" ],
        "CLP"   => [ "name"=>"Chilean Peso","symbol"=>"$" ],
        "CNY"   => [ "name"=>"Chinese Yuan","symbol"=>"¥" ],
        "COP"   => [ "name"=>"Colombian Peso","symbol"=>"$" ],
        "KMF"   => [ "name"=>"Comorian Franc","symbol"=>"CF" ],
        "CDF"   => [ "name"=>"Congolese Franc","symbol"=>"FC" ],
        "CRC"   => [ "name"=>"Costa Rican ColÃ³n","symbol"=>"₡" ],
        "HRK"   => [ "name"=>"Croatian Kuna","symbol"=>"kn" ],
        "CUC"   => [ "name"=>"Cuban Convertible Peso","symbol"=>"$, CUC" ],
        "CZK"   => [ "name"=>"Czech Republic Koruna","symbol"=>"Kč" ],
        "DKK"   => [ "name"=>"Danish Krone","symbol"=>"Kr." ],
        "DJF"   => [ "name"=>"Djiboutian Franc","symbol"=>"Fdj" ],
        "DOP"   => [ "name"=>"Dominican Peso","symbol"=>"$" ],
        "XCD"   => [ "name"=>"East Caribbean Dollar","symbol"=>"$" ],
        "EGP"   => [ "name"=>"Egyptian Pound","symbol"=>"ج.م" ],
        "ERN"   => [ "name"=>"Eritrean Nakfa","symbol"=>"Nfk" ],
        "EEK"   => [ "name"=>"Estonian Kroon","symbol"=>"kr" ],
        "ETB"   => [ "name"=>"Ethiopian Birr","symbol"=>"Nkf" ],
        "EUR"   => [ "name"=>"Euro","symbol"=>"€" ],
        "FKP"   => [ "name"=>"Falkland Islands Pound","symbol"=>"£" ],
        "FJD"   => [ "name"=>"Fijian Dollar","symbol"=>"FJ$" ],
        "GMD"   => [ "name"=>"Gambian Dalasi","symbol"=>"D" ],
        "GEL"   => [ "name"=>"Georgian Lari","symbol"=>"ლ" ],
        "DEM"   => [ "name"=>"German Mark","symbol"=>"DM" ],
        "GHS"   => [ "name"=>"Ghanaian Cedi","symbol"=>"GH₵" ],
        "GIP"   => [ "name"=>"Gibraltar Pound","symbol"=>"£" ],
        "GRD"   => [ "name"=>"Greek Drachma","symbol"=>"₯, Δρχ, Δρ" ],
        "GTQ"   => [ "name"=>"Guatemalan Quetzal","symbol"=>"Q" ],
        "GNF"   => [ "name"=>"Guinean Franc","symbol"=>"FG" ],
        "GYD"   => [ "name"=>"Guyanaese Dollar","symbol"=>"$" ],
        "HTG"   => [ "name"=>"Haitian Gourde","symbol"=>"G" ],
        "HNL"   => [ "name"=>"Honduran Lempira","symbol"=>"L" ],
        "HKD"   => [ "name"=>"Hong Kong Dollar","symbol"=>"$" ],
        "HUF"   => [ "name"=>"Hungarian Forint","symbol"=>"Ft" ],
        "ISK"   => [ "name"=>"Icelandic KrÃ³na","symbol"=>"kr" ],
        "INR"   => [ "name"=>"Indian Rupee","symbol"=>"₹" ],
        "IDR"   => [ "name"=>"Indonesian Rupiah","symbol"=>"Rp" ],
        "IRR"   => [ "name"=>"Iranian Rial","symbol"=>"﷼" ],
        "IQD"   => [ "name"=>"Iraqi Dinar","symbol"=>"د.ع" ],
        "ILS"   => [ "name"=>"Israeli New Sheqel","symbol"=>"₪" ],
        "ITL"   => [ "name"=>"Italian Lira","symbol"=>"L,£" ],
        "JMD"   => [ "name"=>"Jamaican Dollar","symbol"=>"J$" ],
        "JPY"   => [ "name"=>"Japanese Yen","symbol"=>"¥" ],
        "JOD"   => [ "name"=>"Jordanian Dinar","symbol"=>"ا.د" ],
        "KZT"   => [ "name"=>"Kazakhstani Tenge","symbol"=>"лв" ],
        "KES"   => [ "name"=>"Kenyan Shilling","symbol"=>"KSh" ],
        "KWD"   => [ "name"=>"Kuwaiti Dinar","symbol"=>"ك.د" ],
        "KGS"   => [ "name"=>"Kyrgystani Som","symbol"=>"лв" ],
        "LAK"   => [ "name"=>"Laotian Kip","symbol"=>"₭" ],
        "LVL"   => [ "name"=>"Latvian Lats","symbol"=>"Ls" ],
        "LBP"   => [ "name"=>"Lebanese Pound","symbol"=>"£" ],
        "LSL"   => [ "name"=>"Lesotho Loti","symbol"=>"L" ],
        "LRD"   => [ "name"=>"Liberian Dollar","symbol"=>"$" ],
        "LYD"   => [ "name"=>"Libyan Dinar","symbol"=>"د.ل" ],
        "LTL"   => [ "name"=>"Lithuanian Litas","symbol"=>"Lt" ],
        "MOP"   => [ "name"=>"Macanese Pataca","symbol"=>"$" ],
        "MKD"   => [ "name"=>"Macedonian Denar","symbol"=>"ден" ],
        "MGA"   => [ "name"=>"Malagasy Ariary","symbol"=>"Ar" ],
        "MWK"   => [ "name"=>"Malawian Kwacha","symbol"=>"MK" ],
        "MYR"   => [ "name"=>"Malaysian Ringgit","symbol"=>"RM" ],
        "MVR"   => [ "name"=>"Maldivian Rufiyaa","symbol"=>"Rf" ],
        "MRO"   => [ "name"=>"Mauritanian Ouguiya","symbol"=>"MRU" ],
        "MUR"   => [ "name"=>"Mauritian Rupee","symbol"=>"₨" ],
        "MXN"   => [ "name"=>"Mexican Peso","symbol"=>"$" ],
        "MDL"   => [ "name"=>"Moldovan Leu","symbol"=>"L" ],
        "MNT"   => [ "name"=>"Mongolian Tugrik","symbol"=>"₮" ],
        "MAD"   => [ "name"=>"Moroccan Dirham","symbol"=>"MAD" ],
        "MZM"   => [ "name"=>"Mozambican Metical","symbol"=>"MT" ],
        "MMK"   => [ "name"=>"Myanmar Kyat","symbol"=>"K" ],
        "NAD"   => [ "name"=>"Namibian Dollar","symbol"=>"$" ],
        "NPR"   => [ "name"=>"Nepalese Rupee","symbol"=>"₨" ],
        "ANG"   => [ "name"=>"Netherlands Antillean Guilder","symbol"=>"ƒ" ],
        "TWD"   => [ "name"=>"New Taiwan Dollar","symbol"=>"$" ],
        "NZD"   => [ "name"=>"New Zealand Dollar","symbol"=>"$" ],
        "NIO"   => [ "name"=>"Nicaraguan CÃ³rdoba","symbol"=>"C$" ],
        "NGN"   => [ "name"=>"Nigerian Naira","symbol"=>"₦" ],
        "KPW"   => [ "name"=>"North Korean Won","symbol"=>"₩" ],
        "NOK"   => [ "name"=>"Norwegian Krone","symbol"=>"kr" ],
        "OMR"   => [ "name"=>"Omani Rial","symbol"=>".ع.ر" ],
        "PKR"   => [ "name"=>"Pakistani Rupee","symbol"=>"₨" ],
        "PAB"   => [ "name"=>"Panamanian Balboa","symbol"=>"B/." ],
        "PGK"   => [ "name"=>"Papua New Guinean Kina","symbol"=>"K" ],
        "PYG"   => [ "name"=>"Paraguayan Guarani","symbol"=>"₲" ],
        "PEN"   => [ "name"=>"Peruvian Nuevo Sol","symbol"=>"S/." ],
        "PHP"   => [ "name"=>"Philippine Peso","symbol"=>"₱" ],
        "PLN"   => [ "name"=>"Polish Zloty","symbol"=>"zł" ],
        "QAR"   => [ "name"=>"Qatari Rial","symbol"=>"ق.ر" ],
        "RON"   => [ "name"=>"Romanian Leu","symbol"=>"lei" ],
        "RUB"   => [ "name"=>"Russian Ruble","symbol"=>"₽" ],
        "RWF"   => [ "name"=>"Rwandan Franc","symbol"=>"FRw" ],
        "SVC"   => [ "name"=>"Salvadoran ColÃ³n","symbol"=>"₡" ],
        "WST"   => [ "name"=>"Samoan Tala","symbol"=>"SAT" ],
        "SAR"   => [ "name"=>"Saudi Riyal","symbol"=>"﷼" ],
        "RSD"   => [ "name"=>"Serbian Dinar","symbol"=>"din" ],
        "SCR"   => [ "name"=>"Seychellois Rupee","symbol"=>"SRe" ],
        "SLL"   => [ "name"=>"Sierra Leonean Leone","symbol"=>"Le" ],
        "SGD"   => [ "name"=>"Singapore Dollar","symbol"=>"$" ],
        "SKK"   => [ "name"=>"Slovak Koruna","symbol"=>"Sk" ],
        "SBD"   => [ "name"=>"Solomon Islands Dollar","symbol"=>"Si$" ],
        "SOS"   => [ "name"=>"Somali Shilling","symbol"=>"Sh.so." ],
        "ZAR"   => [ "name"=>"South African Rand","symbol"=>"R" ],
        "KRW"   => [ "name"=>"South Korean Won","symbol"=>"₩" ],
        "XDR"   => [ "name"=>"Special Drawing Rights","symbol"=>"SDR" ],
        "LKR"   => [ "name"=>"Sri Lankan Rupee","symbol"=>"Rs" ],
        "SHP"   => [ "name"=>"St. Helena Pound","symbol"=>"£" ],
        "SDG"   => [ "name"=>"Sudanese Pound","symbol"=>".س.ج" ],
        "SRD"   => [ "name"=>"Surinamese Dollar","symbol"=>"$" ],
        "SZL"   => [ "name"=>"Swazi Lilangeni","symbol"=>"E" ],
        "SEK"   => [ "name"=>"Swedish Krona","symbol"=>"kr" ],
        "CHF"   => [ "name"=>"Swiss Franc","symbol"=>"CHf" ],
        "SYP"   => [ "name"=>"Syrian Pound","symbol"=>"LS" ],
        "STD"   => [ "name"=>"São Tomé and Príncipe Dobra","symbol"=>"Db" ],
        "TJS"   => [ "name"=>"Tajikistani Somoni","symbol"=>"SM" ],
        "TZS"   => [ "name"=>"Tanzanian Shilling","symbol"=>"TSh" ],
        "THB"   => [ "name"=>"Thai Baht","symbol"=>"฿" ],
        "TOP"   => [ "name"=>"Tongan Pa'anga","symbol"=>"$" ],
        "TTD"   => [ "name"=>"Trinidad & Tobago Dollar","symbol"=>"$" ],
        "TND"   => [ "name"=>"Tunisian Dinar","symbol"=>"ت.د" ],
        "TRY"   => [ "name"=>"Turkish Lira","symbol"=>"₺" ],
        "TMT"   => [ "name"=>"Turkmenistani Manat","symbol"=>"T" ],
        "UGX"   => [ "name"=>"Ugandan Shilling","symbol"=>"USh" ],
        "UAH"   => [ "name"=>"Ukrainian Hryvnia","symbol"=>"₴" ],
        "AED"   => [ "name"=>"United Arab Emirates Dirham","symbol"=>"إ.د" ],
        "UYU"   => [ "name"=>"Uruguayan Peso","symbol"=>"$" ],
        "USD"   => [ "name"=>"US Dollar","symbol"=>"$" ],
        "UZS"   => [ "name"=>"Uzbekistan Som","symbol"=>"лв" ],
        "VUV"   => [ "name"=>"Vanuatu Vatu","symbol"=>"VT" ],
        "VEF"   => [ "name"=>"Venezuelan BolÃvar","symbol"=>"Bs" ],
        "VND"   => [ "name"=>"Vietnamese Dong","symbol"=>"₫" ],
        "YER"   => [ "name"=>"Yemeni Rial","symbol"=>"﷼" ],
        "ZMK"   => [ "name"=>"Zambian Kwacha","symbol"=>"ZK" ]
    ],

];
